# This workflow will:
# - Create a new Github release
# - Build wheels for supported architectures
# - Deploy the wheels to the Github release
# - Release the static code to PyPi
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Build wheels and deploy

on:
  workflow_dispatch:

jobs:
  setup_release:
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.get_sha.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit SHA
        id: get_sha
        run: echo "version=dev-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_sha.outputs.version }}
          release_name: ${{ steps.get_sha.outputs.version }}

  build_wheels:
    name: Build Wheel
    needs: setup_release
    strategy:
      fail-fast: false
      matrix:
        # Using ubuntu-22.04 instead of 24.04 for more compatibility (glibc).
        os: [ubuntu-22.04]
        python-version: ["3.10", "3.12"]
        torch-version: ["2.9.1"]
        cuda-version: ["12.9.1"]
        cxx11_abi: ["TRUE"]
        package-path: ["hopper"]
        include:
          - os: ARM64
            python-version: "3.10"
            torch-version: "2.9.1"
            cuda-version: "12.9.1"
            cxx11_abi: "TRUE"
            package-path: "hopper"
          - os: ARM64
            python-version: "3.12"
            torch-version: "2.9.1"
            cuda-version: "12.9.1"
            cxx11_abi: "TRUE"
            package-path: "hopper"
    uses: ./.github/workflows/_build.yml
    with:
      runs-on: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      cuda-version: ${{ matrix.cuda-version }}
      torch-version: ${{ matrix.torch-version }}
      cxx11_abi: ${{ matrix.cxx11_abi }}
      release-version: ${{ needs.setup_release.outputs.release-version }}
      upload-to-release: true
      cwd: ${{ matrix.package-path }}

  publish_package:
    name: Publish package
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install ninja packaging wheel twine
          # Install latest setuptools with support for pypi metadata 2.2 (improved compat w/ uv)
          pip install setuptools==75.8.0
          # We don't want to download anything CUDA-related here
          pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Build core package
        env:
          FLASH_ATTENTION_SKIP_CUDA_BUILD: "TRUE"
        run: |
          cd hopper
          python setup.py sdist --dist-dir=../dist
